# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Finca La Peraleña
tagline: Bodas, bautizos, comuniones y eventos en Madrid
email: info@fincalaperalena.com
description: >- # this means to ignore newlines until "baseurl:"
  Finca de bodas, bautizos, comuniones y eventos en entorno natural en Madrid, espacios naturales, gastronomía exclusiva y más de dos décadas de experiencia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fincalaperalena.com" # the base hostname & protocol for your site, e.g. http://example.com
basefolder: ""
keywords: "Finca La Peraleña, Madrid, bodas, exclusivo, finca, eventos, bodas, comuniones, bautizos, celebraciones, eventos de empresa, finca de bodas en Madrid, Madrid, finca de bodas"
locale: es_ES
logo: /assets/images/apple-touch-icon-72x72.png
author:
  name: Finca La Peraleña
  type: LocalBusiness
  telephone: 606022344
  address: Carretera M-501 km 28, Villanueva de Perales 28609, (A 10 min. de Brunete), Madrid

# Listing
show_dir_listing: false

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

collections:
  menu:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      seo:
        name: Finca La Peraleña
        type: LocalBusiness
        telephone: +34606022344
        address: "Carretera M-501 km 28, Villanueva de Perales 28609, (A 10 min. de Brunete), Madrid"

  - scope:
      path: ""
      type: "posts"
    values:
      isPost: true

  - scope:
      path: "assets/fotos/finca/espacios"
    values:
      espacios: true

  - scope:
      path: "assets/fotos/finca/bodas"
    values:
      bodas: true
