# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Finca la Peraleña - Bodas y eventos en Madrid
email: info@fincalaperalena.com
description: >- # this means to ignore newlines until "baseurl:"
  Finca La Peraleña, finca para bodas y eventos ubicada en un entorno natural en Madrid, ofrece espacios naturales, gastronomía exclusiva y experiencia de más de dos décadas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fincalaperalena.com" # the base hostname & protocol for your site, e.g. http://example.com
basefolder: ""
keywords: "Finca La Peraleña, Madrid, bodas, exclusivo, finca, eventos, bodas, comuniones, bautizos, celebraciones, eventos de empresa, finca de bodas en Madrid, Madrid, finca de bodas"
author: "Finca La Peraleña"

# Listing
show_dir_listing: false

# Localhost config
host: 0.0.0.0
port: 4000

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

collections:
  menu:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      isPost: true

  - scope:
      path: "assets/fotos/finca/espacios"
    values:
      espacios: true

  - scope:
      path: "assets/fotos/finca/bodas"
    values:
      bodas: true
